# Configure imput files.
#   markdown : input is markdown
#   ignore_line_breaks : ignore line brakes
#   footnotes : use footnotes
#   definition_lists : use definition list
from: markdown+ignore_line_breaks+footnotes+definition_lists
pdf-engine: lualatex

metadata:
  # CJK(Chinese,Japanese,Korean) main font.
  CJKmainfont: IPAexGothic
  # Title page variables.
  titlepage: true
  titlepage-rule-color: 53565a
  # TOC page standalone.
  toc-own-page: true
  # Centering captions.
  caption-justification: centering
  # ToC Title
  toc-title: 目次
  # ................
  # Changelog
  changelog-title: 更新履歴

# Numbering chapters.
number-sections: true

# Create table of contents, config depth.
table-of-contents: true
toc-depth: 3

# Code highlighting.
highlight-style: tango
listings: true
